### ISSUE TITLE
How to start with my webcam?

### ISSUE THREAD

**Issue by xtodx** [luigifreda/pyslam#1]
How to start my webcam? whatever I do, your video starts up. I use the main_vo.py file.

In dataset.py i found LiveDataset 

To config.ini i added
`[LIVE_DATASET]
type=live
base_path=/dev/video1
name=/dev/video1
cam_settings=settings/KITTI-my.yaml
groundtruth_file=auto`

End set **type=LIVE_DATASET**

I modify the function in dataset.py.
`class LiveDataset(Dataset): 
    def __init__(self, path, name, associations=None, type=DatasetType.VIDEO): 
        super().__init__(path, name, associations, type)    
        self.camera_num = name # use name for camera number
        self.cap = cv2.VideoCapture(self.camera_num) 
        if not self.cap.isOpened():
            raise IOError('Cannot open camera '+self.camera_num)
            
    def getImage(self, frame_id):
        ret, image = self.cap.read()
        if ret is False:
            print('ERROR in reading from camera: ', self.camera_num)
        return self.getImageColor(image)`

because I had error:
**provided image has not the same size as the camera model or image is not grayscale**

Now I have one error

`File "/home/tony/PycharmProjects/pyslam-master/mplot_thread.py", line 206, in setAxis
    self.ax.axis('equal')
  File "/home/tony/.local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1677, in axis
    self.set_aspect('equal', adjustable='datalim')
  File "/home/tony/.local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
`

**Comment by xtodx** [comment]
UPD, matplotlib downgrade to 3.0.3 - error fixed, but slam video don`t work.

**Comment by LoveMeWithoutAll** [comment]
+1

**Comment by luigifreda** [comment]
Hi,
check the new pySLAM v2, in particular, the section _Camera Settings_
https://github.com/luigifreda/pyslam#camera-settings
