### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by Sauly2506** [luigifreda/pyslam#104]
Hi,
Right after installation, I encounter the error "Aborted (core dumped)" after entering "python3 -O main_vo.py" in my terminal. I am using Ubuntu 22.04, and for that reason, I cloned the "ubuntu20" branch. Has anyone experienced similar issues and found a solution?

**Comment by luigifreda** [comment]
Hi, 
thanks for the feedback. 

I assume you followed these instructions 
https://github.com/luigifreda/pyslam/blob/master/PYTHON-VIRTUAL-ENVS.md 

Did the install script successfully install pyenv? 
Did you have any issues during the pip packages installation?

Can you repeat the install procedure after having run the script `clean.sh` in the root folder and share the log you get?
