### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by jiajiaandWu** [luigifreda/pyslam#106]
Your Project is very useful to learn slam,but I have a question that  the VO use Ground True to get the VO scale is OK?

**Comment by luigifreda** [comment]
Did you read the README?

> Main Scripts:
> 
> main_vo.py combines the simplest VO ingredients without performing any image point triangulation or windowed bundle adjustment. At each step , main_vo.py estimates the current camera pose with respect to the previous one. The inter-frame pose estimation returns with. **With this very basic approach, you need to use a ground truth in order to recover a correct inter-frame scale  and estimate a valid trajectory by composing. This script is a first start to understand the basics of inter-frame feature tracking and camera pose estimation**.

> main_slam.py adds feature tracking along multiple frames, point triangulation, keyframe management and bundle adjustment in order to estimate the camera trajectory up-to-scale and build a map. It's still a VO pipeline but it shows some basic blocks which are necessary to develop a real visual SLAM pipeline.
