### ISSUE TITLE
change the optimization cost 

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [luigifreda/pyslam#107]
Do you have any guidance on whether your API provides any support to change the optimisation cost of the reprojection error? For instance, add weights to the points. Have you any advice on how to do this?

**Comment by luigifreda** [comment]
Hi, thanks for your interest. 

The optimization code is based on g2o framework. It already includes robust cost weights and chi2 checks in the local bundle adjustments, as you can easily check: https://github.com/luigifreda/pyslam/blob/master/optimizer_g2o.py

If you need it, you can play with other optimization frameworks and add them. You may want to preliminary test them by using [slamplay](https://github.com/luigifreda/slamplay) for instance.
