### ISSUE TITLE
RGBD extension - guidance  

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [luigifreda/pyslam#108]
Hi,
First of all thank you for the implementation, and for being active and maintaining it.

I am participating in a research project and I am interested in using your code for an RGBD slam system.

Could you please provide any high-level guidance on how I can adapt your code and which components should change to add support for RGBD inputs? Suggesting the file names that I should focus on will be appreciated. 

Certainly, if everything goes according to the plan, I would like to cite your work.

Thank you in advance.

Best,
Panagiotis P.

**Comment by luigifreda** [comment]
Thanks for your feedback. 
Now, pySLAM supports stereo and RGBD cameras too.
All the best for your research project in any case.
Luigi
