### ISSUE TITLE
Loop closure and pose graph optimization

### ISSUE THREAD

**Issue by robofar** [luigifreda/pyslam#109]
Hello.

Does this project include loop closure and pose graph optimization? Or do you know any other python-based SLAM system that has loop closures implemented which I could use, or if you know some python wrapper for ORB_SLAM3 or similar which I could use for easy access to the loop closure and pose graph optimization? It would be very helpful. Thank you

**Comment by luigifreda** [comment]
Hi,
this project includes Python interfaces to g2o with pose optimization and local bundle adjustment. 
https://github.com/luigifreda/pyslam/blob/master/optimizer_g2o.py
You can easily incorporate a pose graph optimization function. As for loop closure, there are many open-source examples. Maybe you want to take a look at this interesting one 
https://github.com/stschubert/VPR_Tutorial
