### ISSUE TITLE
How to add custom feature detection algorithms and feature descriptor sub algorithms?

### ISSUE THREAD

**Issue by MintonLee** [luigifreda/pyslam#110]

**Comment by luigifreda** [comment]
Hi, 

> Is the trajectory error extremely large when calling orb2 and running main_vo.py? Is this normal, or is it a problem with my setup?

Yes, that's something I see on my end too. The ORB2 implementation and keypoint distribution strategy does not seem to be optimal for this specific VO implementation. 

> How to add custom feature detection algorithms and feature descriptor sub algorithms?

This is shortly described here 
https://github.com/luigifreda/pyslam/blob/f754c83e9a18731845ddfe5518eab9bba99df7a8/feature_types.py#L25
