### ISSUE TITLE
Using PySLAM with Point Cloud Data

### ISSUE THREAD

**Issue by Mio-Atse** [luigifreda/pyslam#115]
Thank you for this wonderful work,

I have been working on SLAM for monocular cameras for a while now, and the basis of my work is the segmentation of point clouds. In other words, I am following a different path than the currently used monocular camera methods. For this reason, I need an algorithm that takes point clouds, i.e. x y z r g b as input on the map generation side of the work. Of course, I will also access extra data thanks to the IMU on the UAV. Is it possible to use your work in this way? 

Thanks for your answer in advance.

**Comment by luigifreda** [comment]
Thanks for your feedback. 
Now, pySLAM supports stereo and RGBD cameras too.  If your sensor is an RGBD camera then you can use it.
All the best for your research project.
