### ISSUE TITLE
Can we apply main_vo to "Kagaru Airborne Dataset" ?

### ISSUE THREAD

**Issue by IsaErayy** [luigifreda/pyslam#119]
I need to implement main_vo.py file for "Kagaru Airborne Dataset" where the camera's perspective is downward. I'm stuyding in this problem earlier and I want to learn about  whether getting pose estimation of this dataset with "main_vo" or "main_slam" files is possible or not? Lastly, are there any suggestions to follow for doing this work in right way, what are the steps ? Help is much appreciated.

**Comment by luigifreda** [comment]
Hi,
did you read the main README file? 

`main_vo .py` _"...is a first start to understand the basics of inter-frame feature tracking and camera pose estimation."_

I strongly recommend using `main_slam.py`. 
1) Get your stereo camera calibration and fill in a YAML setting file, such as [this one](https://github.com/luigifreda/pyslam/blob/master/settings/EuRoC_stereo.yaml).
2) Create a new class that inherits from the abstract class `Dataset` (in `dataset.py`) and can read your dataset correctly both in mono and stereo. Add a new corresponding switch entry in `dataset_factory()`.
3) Adjust the main `config.yaml` to trigger your new dataset class and start playing with the slam and its features.
