### ISSUE TITLE
Link to calibration details in README.md is broken

### ISSUE THREAD

**Issue by VladVyskocil** [luigifreda/pyslam#122]
Hi,

Thanks for the great tool! I've noticed that this link in README.md is currently broken (it's the link in Camera calibration section):

https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html

Thanks
Vlad

**Comment by luigifreda** [comment]
Hi Vlad, 
Thank you very much for your feedback! I am glad you like it. 
I fixed the link.

Best,
Luigi
