### ISSUE TITLE
Volumetric Reconstruction Question

### ISSUE THREAD

**Issue by FraDePace** [luigifreda/pyslam#124]
Hi, thanks for your amazing project.

I am interested in volumetric reconstruction with loop closure detection and I would like to ask if there are any differences  between using pyslam with volumetric reconstruction enabled (kUseVolumetricIntegration=True) and PLVS [https://github.com/luigifreda/plvs](url)

thanks!

**Comment by luigifreda** [comment]
Hi,
Thanks for your feedback. That's a good question :-) 
Both pySLAM and PLVS use a keframe-based approach to build a volumetric reconstruction.  For more details, I recommend checking the PLVS [paper](https://arxiv.org/pdf/2309.10896) . 

As you may have noticed, pySLAM and PLVS offer different sets of features. For example, pySLAM provides a variety of local features and loop-closing methods, while PLVS has its own unique capabilities. However, pySLAM is not designed for real-time performance.

In contrast, PLVS, being implemented in C++, supports real-time processing and allows experimentation with various volumetric methods.

Please note that both projects are research frameworks and are still works in progress. More fun is on the way. Stay tuned!
