### ISSUE TITLE
Installation withour sudo

### ISSUE THREAD

**Issue by shashankyld** [luigifreda/pyslam#129]
What is the best way to install pyslam in a computer with no sudo permission and without docker.

**Comment by luigifreda** [comment]
Hi,
I would love to help you, but I’m not sure how to proceed without being able to install the required system packages. In theory, you could download and build everything needed locally (starting from cmake and all the dev basic tools). However, that's a challenge and requires careful management of dependencies and the system paths. 
Good luck!
