### ISSUE TITLE
How could I only use these feature descriptors in my own image set?

### ISSUE THREAD

**Issue by zimoqingfeng** [luigifreda/pyslam#13]
Thanks for such a great work!

It is really valuable for me about these supplied feature descriptors, but how can I just use these descriptors and generate a corresponding visualization in my own pics?

I am looking forward for your replay. 
Nice work again.

**Comment by luigifreda** [comment]
Thanks for your appreciation.
As explained [here](https://github.com/luigifreda/pyslam#user-content-usage), as for feature detection/description/matching, you can start by taking a look at 
- [test/test_feature_manager.py](https://github.com/luigifreda/pyslam/blob/master/test/cv/test_feature_manager.py) (set your image [here](https://github.com/luigifreda/pyslam/blob/master/test/cv/test_feature_manager.py#L29)) 
- [test/test_feature_matching.py](https://github.com/luigifreda/pyslam/blob/master/test/cv/test_feature_matching.py) (set your images [here](https://github.com/luigifreda/pyslam/blob/master/test/cv/test_feature_matching.py#L77))

L

**Comment by zimoqingfeng** [comment]
Thx！
