### ISSUE TITLE
Re-localization and Tracking 

### ISSUE THREAD

**Issue by Zumbalamambo** [luigifreda/pyslam#16]
Great repo! How do I perform relocalization based on the prebuilt map?

**Comment by luigifreda** [comment]
Thanks!
That's work in progress. Those points are listed in the [TODOs](https://github.com/luigifreda/pyslam#user-content-todos). 

Some nice starting points:
- https://github.com/uzh-rpg/netvlad_tf_open
- https://pypi.org/project/pyDBoW3
