### ISSUE TITLE
while undistorting the points error: (-215:Assertion failed) src.isContinuous()

### ISSUE THREAD

**Issue by feritte** [luigifreda/pyslam#21]
Hi Luigi
in camera.py ==> uvs_undistorted = cv2.undistortPoints(np.expand_dims(uvs, axis=1), self.K, self.D, None, self.K) gives this error
in order to fix this, i modified the uvs input :
imagePoints = np.ascontiguousarray(uvs[:, :2]).reshape((uvs.shape[0], 1, 2))
uvs_undistorted = cv2.undistortPoints(imagePoints, self.K, self.D, None, self.K)

**Comment by luigifreda** [comment]
Thank you very much, fixed! I pushed your change.
