### ISSUE TITLE
any tutorial about the parts of the toolbox

### ISSUE THREAD

**Issue by feritte** [luigifreda/pyslam#22]
Hi Luigi,

Thanks again for this great slam toolbox. Considering the capabilities of the pyslam, I would like to know if you have any more detailed docs/tutorials that explain main parts of the toolbox. It would be great for my better understanding of slam process while using the toolbox.

Best

Ferit

**Comment by luigifreda** [comment]
Hi Ferit,
thank you very much for your message. I am working on pyslam during my free time. Documentation is a work in progress :-). In the meanwhile, as for the 'theory' behind, I suggest taking a look at the [suggested material](https://github.com/luigifreda/pyslam#user-content-references) (if you need a refresher).

Best,
Luigi
