### ISSUE TITLE
Adding VIO

### ISSUE THREAD

**Issue by JeffreyYH** [luigifreda/pyslam#26]
Hi Luigi,

Thank you for the nice implementation! I'd like to know if you have any plan to integrate VIO in pyslam. thank you!

Best,

**Comment by luigifreda** [comment]
Thanks for your post :-) 
Yes, in the long-term (not in the next months), I have also considered adding visual-inertial techniques. I love them as well but I tend to think that those are better 'placed' in C++ (given the much higher frequency of the IMU data). Nonetheless, it would also be fun to implement them under python or mixing python-C++.

**Comment by JeffreyYH** [comment]
Thank you for the reply Luigi! Looking forward to seeing VIO added in the future.
