### ISSUE TITLE
Building in pyslam utils

### ISSUE THREAD

**Issue by shumshersubashgautam** [luigifreda/pyslam#28]
Plzz help me to solve this problem.
Scanning dependencies of target pyslam_utils
[ 33%] Building CXX object CMakeFiles/pyslam_utils.dir/utils_module.cpp.o
[ 66%] Building CXX object CMakeFiles/pyslam_utils.dir/utils.cpp.o
In file included from /home/intelligence/pyslam/pyslam/cpp/utils/utils.cpp:2:0:
/home/intelligence/pyslam/pyslam/cpp/utils/utils.h:20:94: error: ‘WARP_FILL_OUTLIERS’ is not a member of ‘cv’
                           const int warp_flags= cv::WARP_INVERSE_MAP + cv::INTER_CUBIC + cv::WARP_FILL_OUTLIERS);
                                                                                              ^~~~~~~~~~~~~~~~~~
/home/intelligence/pyslam/pyslam/cpp/utils/utils.h:27:94: error: ‘WARP_FILL_OUTLIERS’ is not a member of ‘cv’
                           const int warp_flags= cv::WARP_INVERSE_MAP + cv::INTER_CUBIC + cv::WARP_FILL_OUTLIERS);
                                                                                              ^~~~~~~~~~~~~~~~~~
CMakeFiles/pyslam_utils.dir/build.make:86: recipe for target 'CMakeFiles/pyslam_utils.dir/utils.cpp.o' failed
make[2]: *** [CMakeFiles/pyslam_utils.dir/utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/intelligence/pyslam/pyslam/cpp/utils/utils_module.cpp:9:0:
/home/intelligence/pyslam/pyslam/cpp/utils/utils.h:20:94: error: ‘WARP_FILL_OUTLIERS’ is not a member of ‘cv’
                           const int warp_flags= cv::WARP_INVERSE_MAP + cv::INTER_CUBIC + cv::WARP_FILL_OUTLIERS);
                                                                                              ^~~~~~~~~~~~~~~~~~
/home/intelligence/pyslam/pyslam/cpp/utils/utils.h:27:94: error: ‘WARP_FILL_OUTLIERS’ is not a member of ‘cv’
                           const int warp_flags= cv::WARP_INVERSE_MAP + cv::INTER_CUBIC + cv::WARP_FILL_OUTLIERS);
                                                                                              ^~~~~~~~~~~~~~~~~~
/home/intelligence/pyslam/pyslam/cpp/utils/utils_module.cpp: In function ‘void pybind11_init_pyslam_utils(pybind11::module&)’:
/home/intelligence/pyslam/pyslam/cpp/utils/utils_module.cpp:37:152: error: ‘WARP_FILL_OUTLIERS’ is not a member of ‘cv’
      "image"_a,"kps"_a,"patch_size"_a,"use_orientation"_a=true,"scale_factor"_a=1.0,"warp_flags"_a=cv::WARP_INVERSE_MAP + cv::INTER_CUBIC + cv::WARP_FILL_OUTLIERS
                                                                                                                                                 ^~~~~~~~~~~~~~~~~~
CMakeFiles/pyslam_utils.dir/build.make:62: recipe for target 'CMakeFiles/pyslam_utils.dir/utils_module.cpp.o' failed
make[2]: *** [CMakeFiles/pyslam_utils.dir/utils_module.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pyslam_utils.dir/all' failed
make[1]: *** [CMakeFiles/pyslam_utils.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by luigifreda** [comment]
Could you please specify your OS? 
Did you use one of the provided install scripts? All the install scripts install a proper OpenCV version.
It seems that your configuration includes the installation of a very old OpenCV version.
Even OpenCV 3.0.0 include the definition of  cv::WARP_FILL_OUTLIERS 
https://docs.opencv.org/3.0.0/da/d54/group__imgproc__transform.html

**Comment by shumshersubashgautam** [comment]
I tested those in ubuntu  18.04 errors is due to open cv right versions errors  i solved the errors  main_vo.py but  main_slam.py during building pangolin to original  orbslam2 repository  i got lots of errors of eigen3 to..g2opy. how i can solve those problems.now i turned to ubuntu 16.04

**Comment by shumshersubashgautam** [comment]
@luigifreda with these errors.. and plz if u have any ideas to solve the problems of orbslam2 eigens versions to other dependencies errors  plz suggest me.. and from ur repo i got this errors in building ur install_all.sh 
Scanning dependencies of target _pangolin
[  1%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/file_extension.cpp.o
[  2%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/file_utils.cpp.o
[  3%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/threadedfilebuf.cpp.o
[  4%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/sigstate.cpp.o
[  5%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io.cpp.o
[  6%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/uri.cpp.o
[  7%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/timer.cpp.o
[  8%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_exr.cpp.o
[  9%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_jpg.cpp.o
In file included from /usr/include/OpenEXR/ImfHeader.h:51:0,
                 from /usr/include/OpenEXR/ImfInputFile.h:46,
                 from /content/pyslam/thirdparty/pangolin/src/image/image_io_exr.cpp:8:
/usr/include/OpenEXR/ImathVec.h:228:34: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     const Vec2 & normalizeExc () throw (IEX_NAMESPACE::MathExc);
                                  ^~~~~
/usr/include/OpenEXR/ImathVec.h:232:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     Vec2<T>  normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:440:34: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     const Vec3 & normalizeExc () throw (IEX_NAMESPACE::MathExc);
                                  ^~~~~
/usr/include/OpenEXR/ImathVec.h:444:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     Vec3<T>  normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:622:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     const Vec4 &    normalizeExc () throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:626:44: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     Vec4<T>         normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:714:30: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec2<short>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                              ^~~~~
/usr/include/OpenEXR/ImathVec.h:723:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec2<short>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:738:28: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec2<int>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:747:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec2<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                   ^~~~~
/usr/include/OpenEXR/ImathVec.h:762:30: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec3<short>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                              ^~~~~
/usr/include/OpenEXR/ImathVec.h:771:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec3<short>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:786:28: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec3<int>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:795:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec3<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                   ^~~~~
/usr/include/OpenEXR/ImathVec.h:809:30: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec4<short>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                              ^~~~~
/usr/include/OpenEXR/ImathVec.h:818:37: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec4<short>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:833:28: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec4<int>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:842:35: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec4<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                   ^~~~~
/usr/include/OpenEXR/ImathVec.h:1212:26: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec2<T>::normalizeExc () throw (IEX_NAMESPACE::MathExc)
                          ^~~~~
/usr/include/OpenEXR/ImathVec.h:1249:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec2<T>::normalizedExc () const throw (IEX_NAMESPACE::MathExc)
                                 ^~~~~
/usr/include/OpenEXR/ImathVec.h:1704:26: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec3<T>::normalizeExc () throw (IEX_NAMESPACE::MathExc)
                          ^~~~~
/usr/include/OpenEXR/ImathVec.h:1743:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec3<T>::normalizedExc () const throw (IEX_NAMESPACE::MathExc)
                                 ^~~~~
/usr/include/OpenEXR/ImathVec.h:2109:26: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec4<T>::normalizeExc () throw (IEX_NAMESPACE::MathExc)
                          ^~~~~
/usr/include/OpenEXR/ImathVec.h:2150:33: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Vec4<T>::normalizedExc () const throw (IEX_NAMESPACE::MathExc)
                                 ^~~~~
[ 10%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_pango.cpp.o
[ 11%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_png.cpp.o
[ 12%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_ppm.cpp.o
[ 13%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_raw.cpp.o
[ 14%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_tga.cpp.o
[ 14%] Building CXX object src/CMakeFiles/_pangolin.dir/image/image_io_zstd.cpp.o
[ 15%] Building CXX object src/CMakeFiles/_pangolin.dir/image/pixel_format.cpp.o
[ 16%] Building CXX object src/CMakeFiles/_pangolin.dir/log/packet.cpp.o
[ 17%] Building CXX object src/CMakeFiles/_pangolin.dir/log/packetstream.cpp.o
[ 18%] Building CXX object src/CMakeFiles/_pangolin.dir/log/packetstream_reader.cpp.o
[ 19%] Building CXX object src/CMakeFiles/_pangolin.dir/log/packetstream_writer.cpp.o
[ 20%] Building CXX object src/CMakeFiles/_pangolin.dir/log/playback_session.cpp.o
[ 21%] Building CXX object src/CMakeFiles/_pangolin.dir/gl/glchar.cpp.o
[ 22%] Building CXX object src/CMakeFiles/_pangolin.dir/gl/gldraw.cpp.o
[ 23%] Building CXX object src/CMakeFiles/_pangolin.dir/gl/glfont.cpp.o
[ 24%] Building CXX object src/CMakeFiles/_pangolin.dir/gl/glpangoglu.cpp.o
[ 25%] Building CXX object src/CMakeFiles/_pangolin.dir/gl/gltext.cpp.o
[ 26%] Building CXX object src/CMakeFiles/_pangolin.dir/gl/gltexturecache.cpp.o
[ 27%] Building CXX object src/CMakeFiles/_pangolin.dir/display/display.cpp.o
[ 28%] Building CXX object src/CMakeFiles/_pangolin.dir/display/image_view.cpp.o
[ 29%] Building CXX object src/CMakeFiles/_pangolin.dir/display/opengl_render_state.cpp.o
In file included from /content/pyslam/thirdparty/pangolin/include/pangolin/log/packetstream_source.h:5:0,
                 from /content/pyslam/thirdparty/pangolin/include/pangolin/log/packet.h:31,
                 from /content/pyslam/thirdparty/pangolin/src/log/packet.cpp:1:
/content/pyslam/thirdparty/pangolin/include/pangolin/utils/picojson.h: In function ‘bool picojson::_parse(Context&, picojson::input<Iter>&) [with Context = picojson::default_parse_context; Iter = std::istreambuf_iterator<char, std::char_traits<char> >]’:
/content/pyslam/thirdparty/pangolin/include/pangolin/utils/picojson.h:335:12: warning: ‘<anonymous>.picojson::value::u_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         u_ = x.u_;
         ~~~^~~~~~
[ 30%] Building CXX object src/CMakeFiles/_pangolin.dir/display/view.cpp.o
[ 31%] Building CXX object src/CMakeFiles/_pangolin.dir/display/viewport.cpp.o
[ 32%] Building CXX object src/CMakeFiles/_pangolin.dir/handler/handler.cpp.o
[ 33%] Building CXX object src/CMakeFiles/_pangolin.dir/handler/handler_glbuffer.cpp.o
[ 34%] Building CXX object src/CMakeFiles/_pangolin.dir/handler/handler_image.cpp.o
[ 34%] Building CXX object src/CMakeFiles/_pangolin.dir/plot/datalog.cpp.o
[ 35%] Building CXX object src/CMakeFiles/_pangolin.dir/plot/plotter.cpp.o
[ 36%] Building CXX object src/CMakeFiles/_pangolin.dir/var/input_record_repeat.cpp.o
[ 37%] Building CXX object src/CMakeFiles/_pangolin.dir/var/vars.cpp.o
[ 38%] Building CXX object src/CMakeFiles/_pangolin.dir/display/widgets/widgets.cpp.o
[ 39%] Building CXX object src/CMakeFiles/_pangolin.dir/video/stream_encoder_factory.cpp.o
[ 40%] Building CXX object src/CMakeFiles/_pangolin.dir/video/video.cpp.o
[ 41%] Building CXX object src/CMakeFiles/_pangolin.dir/video/video_input.cpp.o
[ 42%] Building CXX object src/CMakeFiles/_pangolin.dir/video/video_interface_factory.cpp.o
[ 43%] Building CXX object src/CMakeFiles/_pangolin.dir/video/video_output.cpp.o
[ 44%] Building CXX object src/CMakeFiles/_pangolin.dir/video/video_output_interface_factory.cpp.o
[ 45%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/test.cpp.o
[ 46%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/images.cpp.o
[ 47%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/images_out.cpp.o
[ 48%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/split.cpp.o
[ 49%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/pvn.cpp.o
[ 50%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/pango.cpp.o
[ 51%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/pango_video_output.cpp.o
[ 52%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/debayer.cpp.o
[ 53%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/shift.cpp.o
[ 54%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/mirror.cpp.o
[ 54%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/unpack.cpp.o
[ 55%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/join.cpp.o
[ 56%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/merge.cpp.o
[ 57%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/json.cpp.o
In file included from /content/pyslam/thirdparty/pangolin/include/pangolin/platform.h:81:0,
                 from /content/pyslam/thirdparty/pangolin/include/pangolin/pangolin.h:30,
                 from /content/pyslam/thirdparty/pangolin/include/pangolin/video/drivers/mirror.h:30,
                 from /content/pyslam/thirdparty/pangolin/src/video/drivers/mirror.cpp:28:
/content/pyslam/thirdparty/pangolin/src/video/drivers/mirror.cpp: In member function ‘void pangolin::MirrorVideo::Process(unsigned char*, const unsigned char*)’:
/content/pyslam/thirdparty/pangolin/include/pangolin/utils/log.h:37:42: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #   define pango_print_warn(...)  fprintf(stderr, __VA_ARGS__)
                                   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/content/pyslam/thirdparty/pangolin/src/video/drivers/mirror.cpp:158:13: note: in expansion of macro ‘pango_print_warn’
             pango_print_warn("MirrorVideo::Process(): Invalid enum %i.\n", flips[s]);
             ^~~~~~~~~~~~~~~~
/content/pyslam/thirdparty/pangolin/src/video/drivers/mirror.cpp:159:9: note: here
         case MirrorOptionsNone:
         ^~~~
[ 58%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/thread.cpp.o
[ 59%] Building CXX object src/CMakeFiles/_pangolin.dir/tools/video_viewer.cpp.o
[ 60%] Building CXX object src/CMakeFiles/_pangolin.dir/display/device/display_x11.cpp.o
[ 61%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/posix/condition_variable.cpp.o
[ 62%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/posix/semaphore.cpp.o
[ 63%] Building CXX object src/CMakeFiles/_pangolin.dir/utils/posix/shared_memory_buffer.cpp.o
[ 64%] Building CXX object src/CMakeFiles/_pangolin.dir/console/ConsoleView.cpp.o
[ 65%] Building CXX object src/CMakeFiles/_pangolin.dir/python/PyInterpreter.cpp.o
[ 66%] Building CXX object src/CMakeFiles/_pangolin.dir/python/PyModulePangolin.cpp.o
[ 67%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/firewire.cpp.o
[ 68%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/deinterlace.cpp.o
[ 69%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/v4l.cpp.o
[ 70%] Building CXX object src/CMakeFiles/_pangolin.dir/video/drivers/ffmpeg.cpp.o
[ 71%] Building C object src/CMakeFiles/_pangolin.dir/fonts.c.o
[ 72%] Linking CXX static library lib_pangolin.a
[ 72%] Built target _pangolin
Scanning dependencies of target pangolin
Scanning dependencies of target SimpleScene
Scanning dependencies of target SimplePlot
Scanning dependencies of target SimpleMultiDisplay
Scanning dependencies of target SimpleVideo
Scanning dependencies of target SimpleDisplay
Scanning dependencies of target HelloPangolin
Scanning dependencies of target SimpleDisplayImage
[ 73%] Building CXX object examples/SimplePlot/CMakeFiles/SimplePlot.dir/main.cpp.o
[ 74%] Building CXX object examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/main.cpp.o
[ 75%] Building CXX object examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/main.cpp.o
[ 75%] Building CXX object examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/main.cpp.o
[ 76%] Building CXX object examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/main.cpp.o
[ 77%] Building CXX object examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/main.cpp.o
[ 78%] Building CXX object examples/SimpleScene/CMakeFiles/SimpleScene.dir/main.cpp.o
[ 79%] Building CXX object python/CMakeFiles/pangolin.dir/pangolin.cpp.o
[ 80%] Linking CXX executable HelloPangolin
[ 81%] Linking CXX executable SimplePlot
[ 82%] Linking CXX executable SimpleDisplayImage
[ 83%] Linking CXX executable SimpleMultiDisplay
[ 84%] Linking CXX executable SimpleVideo
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/build.make:102: recipe for target 'examples/HelloPangolin/HelloPangolin' failed
make[2]: *** [examples/HelloPangolin/HelloPangolin] Error 1
CMakeFiles/Makefile2:328: recipe for target 'examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all' failed
make[1]: *** [examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/build.make:102: recipe for target 'examples/SimpleDisplayImage/SimpleDisplayImage' failed
make[2]: *** [examples/SimpleDisplayImage/SimpleDisplayImage] Error 1
CMakeFiles/Makefile2:438: recipe for target 'examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/all' failed
make[1]: *** [examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/SimplePlot/CMakeFiles/SimplePlot.dir/build.make:102: recipe for target 'examples/SimplePlot/SimplePlot' failed
make[2]: *** [examples/SimplePlot/SimplePlot] Error 1
CMakeFiles/Makefile2:548: recipe for target 'examples/SimplePlot/CMakeFiles/SimplePlot.dir/all' failed
make[1]: *** [examples/SimplePlot/CMakeFiles/SimplePlot.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/build.make:102: recipe for target 'examples/SimpleVideo/SimpleVideo' failed
make[2]: *** [examples/SimpleVideo/SimpleVideo] Error 1
CMakeFiles/Makefile2:658: recipe for target 'examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/all' failed
make[1]: *** [examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/all] Error 2
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/build.make:102: recipe for target 'examples/SimpleMultiDisplay/SimpleMultiDisplay' failed
make[2]: *** [examples/SimpleMultiDisplay/SimpleMultiDisplay] Error 1
CMakeFiles/Makefile2:383: recipe for target 'examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/all' failed
make[1]: *** [examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/all] Error 2
In file included from /content/pyslam/thirdparty/pangolin/python/gl/gl.hpp:5:0,
                 from /content/pyslam/thirdparty/pangolin/python/pangolin.cpp:24:
/content/pyslam/thirdparty/pangolin/python/gl/colour.hpp: In function ‘void pangolin::declareColour(pybind11::module&)’:
/content/pyslam/thirdparty/pangolin/python/gl/colour.hpp:14:33: warning: unused parameter ‘m’ [-Wunused-parameter]
 void declareColour(py::module & m) {
                                 ^
[ 85%] Linking CXX executable SimpleScene
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/SimpleScene/CMakeFiles/SimpleScene.dir/build.make:102: recipe for target 'examples/SimpleScene/SimpleScene' failed
make[2]: *** [examples/SimpleScene/SimpleScene] Error 1
CMakeFiles/Makefile2:493: recipe for target 'examples/SimpleScene/CMakeFiles/SimpleScene.dir/all' failed
make[1]: *** [examples/SimpleScene/CMakeFiles/SimpleScene.dir/all] Error 2
[ 86%] Linking CXX executable SimpleDisplay
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/build.make:102: recipe for target 'examples/SimpleDisplay/SimpleDisplay' failed
make[2]: *** [examples/SimpleDisplay/SimpleDisplay] Error 1
CMakeFiles/Makefile2:603: recipe for target 'examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/all' failed
make[1]: *** [examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/all] Error 2
[ 87%] Linking CXX shared module ../../pangolin.cpython-36m-x86_64-linux-gnu.so
[ 87%] Built target pangolin
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by luigifreda** [comment]
Given this: 
`/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to _glapi_tls_Current' collect2: error: ld returned 1 exit status examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/build.make:102: recipe for target 'examples/HelloPangolin/HelloPangolin' failed make[2]: *** [examples/HelloPangolin/HelloPangolin] Error 1 CMakeFiles/Makefile2:328: recipe for target 'examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all' failed make[1]: *** [examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libGL.so: undefined reference to _glapi_tls_Current'`
you need to install opengl on your system 
https://medium.com/@theorose49/install-opengl-at-ubuntu-18-04-lts-31f368d0b14e
