### ISSUE TITLE
Videos without groundtruth

### ISSUE THREAD

**Issue by adizhol** [luigifreda/pyslam#30]
Hello,

Thank you for this useful repo.
How can I run the vo and slam on videos without ground truth?

Thanks

**Comment by mihailk239** [comment]
You can generate zero groundtruth

**Comment by luigifreda** [comment]
Hi @adizhol 
thank you for the message. 
As explained in the README, you need a ground truth only with` main_vo.py`. You do **NOT** need any grountruth with `main_slam.py`. 
So, when running `main_slam.py` you can actually ignore the groundtruth entry in `config.ini`: the script will actually ignore it as well 
https://github.com/luigifreda/pyslam/blob/master/main_slam.py#L58

**Comment by abcabc456** [comment]
Hello，
Thank you for this useful repo.
What is the format of groundtruth for various data types？
Thanks
