### ISSUE TITLE
Can't find 'install_all_mac_venv.sh' file

### ISSUE THREAD

**Issue by Brian-ZhenLiu** [luigifreda/pyslam#33]
To install pyslam under macOS, I just followed the instructions to run './install_all_mac_venv.sh', however, there is not a file's name is 'install_all_mac_venv.sh'.  So, I just wonder that how to launch the macOS install script? Thanks.

**Comment by luigifreda** [comment]
Hi,
thanks for your interest. You need to read the instructions [here](https://github.com/luigifreda/pyslam/blob/master/MAC.md).

Please, follow these install steps:
1. first you need to install homebrew and Xcode CLT 
2. download this repo and **move to the experimental mac branch**:
```
   $ git clone https://github.com/luigifreda/pyslam.git 
   $ cd pyslam 
   $ git checkout mac 

```
Did you run `$ git checkout mac `? Once you've run it, you will find the file `install_all_mac_venv.sh`

**Comment by Brian-ZhenLiu** [comment]
Thanks for your reply. It works.
When I run the VO version, there is an error occurs: 'ERROR while reading the file' when it tried to read the video in the end. May I ask how to deal with this?
 ![image](https://user-images.githubusercontent.com/32280695/90432564-b6845c80-e098-11ea-9a83-0d0cbfd4560e.png)

**Comment by luigifreda** [comment]
Can you play that file separately?
