### ISSUE TITLE
Question about camera settings

### ISSUE THREAD

**Issue by stelaago** [luigifreda/pyslam#34]
Dear Luigi, 
When I use the TUM dataset and I have to edit the file about the camera settings, I'm not sure about some parameters.
What is the meaning of **fps, IR and depth**? Where can I find these values?

Thank you in advance

**Comment by luigifreda** [comment]
Hi,
as for the camera parameters, you can take a look here 
https://docs.opencv.org/master/d4/d94/tutorial_camera_calibration.html 
and here 
https://github.com/luigifreda/pyslam/blob/master/camera.py 

fps = Frames Per Second

as for the other parameters, you can take a look at the code of ORBSLAM2 where they are actually used in a STEREO or RGBD context.
