### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kevkid** [luigifreda/pyslam#35]
Hi, I am new to robotics and SLAM in general. I was hoping for some guidance in using this tool. I want to be able to generate a map from a self propelling robot with one camera and have the bot localize itself. I think this is the right toolkit to use. I just don't know where to start. Could I just try this with a webcam and start generating a map of a room?

**Comment by luigifreda** [comment]
Thanks for your comment. pyslam is mainly made for experimenting and playing with SLAM and local features. 

If you want to work on a real robot you need real-time capabilities. You can take a look at ORBSLAM3 for instance. 

As for starting with SLAM, I strongly suggest taking a look at the material suggested [here](https://github.com/luigifreda/pyslam#references). In particular, the slides of Prof. Scaramuzza's course are a great start IMO. 

If you want to play with your camera and pyslam, start from this [section](https://github.com/luigifreda/pyslam#camera-settings).
