### ISSUE TITLE
Calibrate.py issue 

### ISSUE THREAD

**Issue by theshrek1** [luigifreda/pyslam#37]
When I run calibrate.py it gives me a traceback:  line 61, in <module> 
h, w = cv.imread(img_names[0], cv.IMREAD_GRAYSCALE).shape[:2]  # TODO: use imquery call to retrieve results
IndexError: list index out of range.

**Comment by luigifreda** [comment]
Which is the sequence of commands you launched for your calibration? Did you preliminary acquired a sequence of images where the chessboard can be detected some with `grab_chessboard_images.py`?
Take a [look](https://github.com/luigifreda/pyslam#camera-settings) at this section if you didn't.
