### ISSUE TITLE
Using Depth information for TUM dataset

### ISSUE THREAD

**Issue by MohomedShalik** [luigifreda/pyslam#39]
I ran main_slam.py for a TUM dataset, I noticed that depth information is not used. I'm using this to estimate extrinsic camera parameters, is there a way to use depth images to increase the accuracy?

**Comment by luigifreda** [comment]
You can take a look at the ORBSLAM2 (or version 3) approach. You can find paper and code here
https://github.com/raulmur/ORB_SLAM2
