### ISSUE TITLE
What is the setting for "main-slam-kitti-map"?

### ISSUE THREAD

**Issue by hyeonhoshin** [luigifreda/pyslam#42]
Dear luigifreda,

I'm trying to find in order to find the parameter settings same as "main-slam-kitti-map".

But, even though I tried increasing  _kTrackingWaitForLocalMappingSleepTime_, and _kTrackingWaitForLocalMappingToGetIdle=True_, a path diverges at 800 frame in kitti 06 seq.

Could you please let me know **the parameters used for generating "main-slam-kitti-map"** using this program, please?

(I guessed you used SUPERPOINT and some parameter tweak.

But I failed all possible combination I knew)

Thank you.

![image](https://user-images.githubusercontent.com/35714982/102618431-1f323180-417e-11eb-9a11-23f7607e438d.png)

**Comment by luigifreda** [comment]
I've just taken this snapshot this morning without touching anything (default config with ORB2)

![kitti-orb2-again](https://user-images.githubusercontent.com/10080262/102686655-4a059f80-41e9-11eb-9c55-b8e5b68efc42.png)

**Comment by hyeonhoshin** [comment]
Thank you so much!
