### ISSUE TITLE
AttributeError: module 'g2o' has no attribute 'Flag'

### ISSUE THREAD

**Issue by JeffreyYH** [luigifreda/pyslam#43]
Hi, when I tried to run main_slam.py, it shows AttributeError: module 'g2o' has no attribute 'Flag'.

Thank you!

**Comment by luigifreda** [comment]
Hi,
some questions:
- which is your OS? 
- which install script did you use? 

That message means pyslam is not using the custom g2o that needs to be compiled via the install scripts.

**Comment by JeffreyYH** [comment]
Thanks for your reply Luigi,
 I am using Ubuntu 18.04 and I used install_thirdparty.sh to install g2o.

**Comment by luigifreda** [comment]
I cleaned with `$ ./clean.sh` and launched again a new install with `./install_all.sh` and everything runs correctly. 
Can you please check that you have a file like `thirdparty/g2opy/lib/g2o.cpython-36m-x86_64-linux-gnu.so`?

**Comment by JeffreyYH** [comment]
Thanks for the kind explanation, Luigi.

I pulled the new changes and remove my previous g2opy and g2o(cpp) installation and reinstalled third_party by running `./install_thirdparty.sh `and `./install_cpp.sh`. But the problem remains.

The reason that I did not use the script install_all.sh directly is that I need different versions of some python dependencies (e,g. pytorch). But I don't think that is a issue, right?

**Comment by luigifreda** [comment]
Do you have rsync installed? 
Did you run the script `install_basic.sh`? 

Please, make sure that the actual commands are executed
![Screenshot from 2021-03-22 23-16-36](https://user-images.githubusercontent.com/10080262/112065377-d61ac080-8b64-11eb-920b-b1b9ab3c65e4.png)

**Comment by JeffreyYH** [comment]
Yes, I run install_all.sh and the problem remains.

**Comment by luigifreda** [comment]
Could you please answer the following questions? 

1. Do you have another installation of g2o for python?
If yes, could you please try to modify its base folder path temporarily and launch main_slam.py again just to check if there is an interference with the lib paths?

2. Could you please make sure that the following commands are executed 
https://user-images.githubusercontent.com/10080262/112065377-d61ac080-8b64-11eb-920b-b1b9ab3c65e4.png

**Comment by diametrical** [comment]
Hi Luigi,

I did not use the install_all.sh at first and download all the deps by myself. After I found this thread, I ran the 
./clean.sh and  ran the $ ./install_all.sh. However, I still have the same issue.
module 'g2o' has no attribute 'Flag'.

following outputs after running 
  rsync ./g2opy_changes/types_six_dof_expmap.h ./g2opy/python/types/sba/types_six_dof_expmap.h

Output is 

rsync: change_dir "/home/diam/Downloads/pyslam-master/g2opy//./g2opy_changes" failed: No such file or directory (2)
rsync: change_dir#3 "/home/diam/Downloads/pyslam-master/g2opy//./g2opy/python/types/sba" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.1]

**Comment by diametrical** [comment]
Got the same issue, as I installed the g2opy by myself with the wrong branch.

Issued solved by running rsync and make a python3 setup.py install 

    G2OPY_REVISION=5587024
    git checkout $G2OPY_REVISION
    rsync ./g2opy_changes/types_six_dof_expmap.h ./g2opy/python/types/sba/types_six_dof_expmap.h
    rsync ./g2opy_changes/sparse_optimizer.h ./g2opy/python/core/sparse_optimizer.h   
    rsync ./g2opy_changes/python_CMakeLists.txt ./g2opy/python/CMakeLists.txt   
    cd build
    cmake .. $EXTERNAL_OPTION
    make -j8
    cd ..
    python3 setup.py install
