### ISSUE TITLE
tensorflow-gpu-1.14.0

### ISSUE THREAD

**Issue by Paul44444** [luigifreda/pyslam#44]
Recently I tried to install pyslam on Linux (Python 3.8) with ./install_all.sh. 
Unfortunately, it always returns the error :

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0
ERROR: No matching distribution found for tensorflow-gpu==1.14.0

I did install tensorflow and also tensorflow-gpu, but with a new version. When I try to install 

pip3 install tensorflow-gpu==1.14

it returns the same error:

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14
ERROR: No matching distribution found for tensorflow-gpu==1.14

What can I do? It seems, that this exact version of tensorflow-gpu is required, while at the 
same time, it cannot be installed. 
For any advice, I would be very happy!
Thank you in advance.

**Comment by luigifreda** [comment]
I have python 3.6.9 under my ubuntu 18 and that's the required version. 
Python 3.8 does not support TensorFlow 1.14.0. 

You can try to use the install procedure described here: 
https://github.com/luigifreda/pyslam/blob/master/PYTHON-VIRTUAL-ENVS.md 
This will install a custom python environment with python 3.6.9 and pyslam in it.
