### ISSUE TITLE
How to run vo on my own data?

### ISSUE THREAD

**Issue by lidehuihxjz** [luigifreda/pyslam#47]
Hello!
How to run vo on my own data without groundtruth?

**Comment by luigifreda** [comment]
Hi,
if you mean that you want to run `main_vo.py` without groundtruth, this question was already answered here:
https://github.com/luigifreda/pyslam/issues/30#issuecomment-667490838 
I would consider `main_vo.py` as a toy/educational example (as explained in the README). It actually does need the knowledge of a groundtruth for estimating the inter-frame scale.
