### ISSUE TITLE
error when running main_slam with latest OrderedSet

### ISSUE THREAD

**Issue by diametrical** [luigifreda/pyslam#48]
Hi,
I got following error when run the main_slam

  File "/home/dam/.local/lib/python3.5/site-packages/ordered_set.py", line 134, in copy
    return self.__class__(self)
  File "/home/dam/.local/lib/python3.5/site-packages/ordered_set.py", line 69, in __init__
    self |= iterable
TypeError: unsupported operand type(s) for |=: 'OrderedSet' and 'OrderedSet'

Issue solved by installing lower version of OrderedSet 

pip install ordered-set==3.1.1

**Comment by luigifreda** [comment]
Thank you very much for this sharing this! I never hit such an isue. My current ordered-set package version is indeed 3.1.1. 
I'll add a link to this note in the TROUBLESHOOTING file.
