### ISSUE TITLE
installing and testing pyslam under Windows

### ISSUE THREAD

**Issue by luigifreda** [luigifreda/pyslam#51]
Many people asked me how to install and test pyslam under Windows. 
I would suggest going with Windows WSL2 and install ubuntu under it. 
Didn't test it yet but I found this cool install procedure that should provide a fast ubuntu GUI under Windows
https://www.youtube.com/watch?v=IL7Jd9rjgrM 

WIP ...

**Comment by SionHu** [comment]
Got this repo to work flawlessly with WSL2 under Windows 10!! Thank you for the great documentation!

**Comment by luigifreda** [comment]
Awesome! Thanks for sharing your experience!

**Comment by SionHu** [comment]
No problem!! Just so you know, there was one hiccup that I encountered during the building of g2opy regarding the Eigen quaternion member access. I followed[ this pull request ](https://github.com/uoip/g2opy/pull/52) of g2opy official repo and got it to work. Maybe you can include this in your README in case anyone else has similar problems. 😄

**Comment by luigifreda** [comment]
That hiccup is really strange! I've managed that problem here:

**Comment by luigifreda** [comment]
I've just checked both under docker and with a real Ubuntu 20 install that g2opy get compiled correctly under the `ubuntu20` branch.

**Comment by luigifreda** [comment]
Hi,
you can't use `main_vo.py` on TUM datasets. 
This is well explained in the REAMDE 
![Screenshot from 2022-03-18 18-27-37](https://user-images.githubusercontent.com/10080262/159053535-29a55ec3-3373-4163-9b05-411efd0b634e.png)

Indeed, with  `main_vo.py`

*you need to use a ground truth in order to recover a correct inter-frame scale s and estimate a valid trajectory by composing $C_k = C_{k-1} * [R_{k-1,k}, s t_{k-1,k}]$.*
**This script is a first start to understand the basics of inter-frame feature tracking and camera pose estimation.**

You need the full `main_slam.py` in order to run other datasets.

**Comment by zxl152723** [comment]
1

**Comment by zxl152723** [comment]
> Hi, you can't use `main_vo.py` on TUM datasets. This is well explained in the REAMDE ![Screenshot from 2022-03-18 18-27-37](https://user-images.githubusercontent.com/10080262/159053535-29a55ec3-3373-4163-9b05-411efd0b634e.png)
> 
> Indeed, with `main_vo.py`
> 
> _you need to use a ground truth in order to recover a correct inter-frame scale s and estimate a valid trajectory by composing $C_k = C_{k-1} * [R_{k-1,k}, s t_{k-1,k}]$._ **This script is a first start to understand the basics of inter-frame feature tracking and camera pose estimation.**
> 
> You need the full `main_slam.py` in order to run other datasets.

Thank you so much for your guidance, this pySLAM project of yours is really nice.

**Comment by zxl152723** [comment]
when I run main_slam.py&nbsp; &nbsp;The following error occurs&nbsp;
Traceback (most recent call last):
&nbsp; File "main_slam.py", line 29, in <module&gt;
&nbsp; &nbsp; from slam import Slam, SlamState
&nbsp; File "/mnt/d/pyslam-master/slam.py", line 35, in <module&gt;
&nbsp; &nbsp; from map import Map
&nbsp; File "/mnt/d/pyslam-master/map.py", line 41, in <module&gt;
&nbsp; &nbsp; import optimizer_g2o
&nbsp; File "/mnt/d/pyslam-master/optimizer_g2o.py", line 36, in <module&gt;
&nbsp; &nbsp; def bundle_adjustment(keyframes, points, local_window, fixed_points=False, verbose=False, rounds=10, use_robust_kernel=False, abort_flag = g2o.Flag()):
AttributeError: module 'g2o' has no attribute 'Flag'

**Comment by zxl152723** [comment]
when I run main_slam    The following error 

![868bfb7b726ba6d42db0836e694d66d](https://user-images.githubusercontent.com/73846756/159173671-9ad2939b-f3ab-4a2f-9e06-b09e1beb853f.png)

**Comment by zxl152723** [comment]
Hello, I used main_slam.py to run the TUM dataset, but I only want the function of visual odometry, no need to map, how should I change it in the pySLAM program? Or what features are turned off?

**Comment by Raman-RISE** [comment]
> I run pySLAM under win10, and only run the visual odometer that is main_vo.py. The trajectory error on the Kitti data set is very small, as shown in the first figure, but the results are basically incorrect when running the TUM data set, as shown in the second as shown in the figure. I have changed the camera parameters in the program, why is this? I have tried several TUM datasets and they are all wrong~ I can't find where the problem is~ ![dd1431f58a88e81f6d990c16a61ba0b](https://user-images.githubusercontent.com/73846756/159048448-fe71d0e0-4ee1-491d-9961-2d5be57a1baf.png) ![a0eb721764e4f56881829f1ba864a72](https://user-images.githubusercontent.com/73846756/159048492-2fb845dc-5ba5-42d0-a1c4-21962f1158de.png)

Is it possible to run it directly on Win10 without WSL?

**Comment by Raman-RISE** [comment]
> I run pySLAM under win10, and only run the visual odometer that is main_vo.py. The trajectory error on the Kitti data set is very small, as shown in the first figure, but the results are basically incorrect when running the TUM data set, as shown in the second as shown in the figure. I have changed the camera parameters in the program, why is this? I have tried several TUM datasets and they are all wrong~ I can't find where the problem is~ ![dd1431f58a88e81f6d990c16a61ba0b](https://user-images.githubusercontent.com/73846756/159048448-fe71d0e0-4ee1-491d-9961-2d5be57a1baf.png) ![a0eb721764e4f56881829f1ba864a72](https://user-images.githubusercontent.com/73846756/159048492-2fb845dc-5ba5-42d0-a1c4-21962f1158de.png)

Is it possible to run it on Win10 directly without WSL? How did you install it?

**Comment by luigifreda** [comment]
As for questions/clarifications related to `main_vo.py`, see issue #230

I added a related section in the troubleshooting document too.
