### ISSUE TITLE
How to use my modified superpoint model

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [luigifreda/pyslam#57]
I have modified backbone of superpoint, and I want to apply my model to this project. But I donnt konw ur node name of "pyslam/thirdparty/superpoint/superpoint_v1.pth". PLZ help me~ thank you!

**Comment by luigifreda** [comment]
Hi,
you need to modify the weights path in the class `SuperPointOptions`: https://github.com/luigifreda/pyslam/blob/master/feature_superpoint.py#L40
