### ISSUE TITLE
The "video_color.mp4" is not a valid video file

### ISSUE THREAD

**Issue by zyqdragon** [luigifreda/pyslam#64]
The "video_color.mp4" is not a valid video file so that the "python3 -O main_vo.py" can't run correctly. Can anyone provide the valid video file of "video_color.mp4"?

**Comment by luigifreda** [comment]
Hi,
you need to download the color datasets from this page. This is explained in the main README
https://github.com/luigifreda/pyslam#kitti-datasets 
Namely, search for the link "Download odometry data set (color, 65 GB)" in the KITTI home page 
http://www.cvlibs.net/datasets/kitti/eval_odometry.php
