### ISSUE TITLE
Which code file to start with just for computing VO from monocular images?

### ISSUE THREAD

**Issue by Mechazo11** [luigifreda/pyslam#68]
Dear @luigifreda,

Thank you for publishing your work as open-source. I am relatively new to the field of VO and currently working on a novel VO system that incorporates semantic information for place recognition. 

A part of my system can compute key points and their descriptions using ORB in consecutive images using OpenCV.

My question are:
1. Which scripts from your code repository should I start with that would compute VO given two sets of key points from two images (say t_0 and t_1)

2. You mentioned ORB was improved upon in the ORB2-SLAM paper. Are those improvements already part of OpenCV or are they user-defined functions found in the python scripts in your repository? I am using OpenCV 4.2

3. Is the camera calibration code available in your repo?

Thank you for your time.

With best,
Azmyin

**Comment by luigifreda** [comment]
Hi,
first, please take a look a the README. You can get there a reply to 1 and 3.

**1**
![Screenshot from 2022-03-18 18-27-37](https://user-images.githubusercontent.com/10080262/159056291-14839c6b-9903-4e68-9a09-95a3f23cb9ff.png)

**3**
https://github.com/luigifreda/pyslam#camera-settings 

As for point **2**, no, that version of ORB (from ORBSLAM2) is NOT part of OpenCV. 
Hope this helps. 
- L -
