### ISSUE TITLE
"actually create the virtual environment" part of code was not executed in pyenv-create.sh 

### ISSUE THREAD

**Issue by zhuoqun-chen** [luigifreda/pyslam#69]
Hi, luigifreda!

I'm using Ubuntu20.04, after I
```bash
git checkout ubuntu20
```

The part of code in `pyenv-create.sh `:

```bash
# actually create the virtual environment 
if [ ! -d $ENV_PATH/bin ]; then 
    print_blue creating virtual environment $ENV_NAME with python version $PYSLAM_PYTHON_VERSION
    pyenv install -v $PYSLAM_PYTHON_VERSION
    pyenv local $PYSLAM_PYTHON_VERSION
    python3 -m venv $ENV_NAME
fi 
```
was not executed, so python `3.6.9` version was not created, and this directly resulted in the failure of the installation of `tensorflow-estimator==1.14.0`, because python `3.8` in my system prevent finding it, and the error is:

`ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0 (from versions: 2.2.0, ... , 2.8.0)`

## 
How can I fix this? Expecting your precious solution, Thanks!

**Comment by luigifreda** [comment]
Hi,
could you check if you have a folder `~/.python/venvs/pyslam/`? 
If yes then try to remove that folder and run again 
```
. pyenv-create.sh
```
Please, do not forget the dot! (don't use  '/' !)
as explained here: https://github.com/luigifreda/pyslam/blob/ubuntu20/PYTHON-VIRTUAL-ENVS.md
