### ISSUE TITLE
A reference for Homography transformation in regenerated Image 2

### ISSUE THREAD

**Issue by farhadinima75** [luigifreda/pyslam#71]
Hi there.
I'm trying to find a paper that used second image transformed from first image (artificial Homography in reprojection error) as a evaluation method.

This repo use the following procedure:
```
# optionally regenerate the second image (override) by transforming the first image with a rotation or homography (here you have a ground-truth)
img2, img2_box, H2 = transform_img(img1, rotx=20, roty=30, rotz=40, tx=0, ty=0, scale=1.05, adjust_frame=True)   # homography
``` 
And then we can use this `H2` for reprojection error calculation.
Is there any paper that I can find?
Any help would be appreciated.

**Comment by luigifreda** [comment]
Hi,
I am not sure to understand your question. 

Are you not familiar with homographies? If yes, you may want to take a look at  [Multiple View Geometry in Computer Vision](https://www.robots.ox.ac.uk/~vgg/hzbook/) by Richard Hartley and Andrew Zisserman.
When you have a pure camera rotation, the transformation of the image points from one camera image to another (assuming there is no camera distortion) is modeled by a homography.
A perspective transformation between two planes is modeled via a homography. In other words, when you have a planar target moving in front of the camera (assuming no camera distortion), again, the transformations between corresponding image points are modeled with homographies. For instance 
https://docs.opencv.org/3.4/d1/de0/tutorial_py_feature_homography.html 

As for a paper, you may want to take a look at this one
https://www.robots.ox.ac.uk/~vgg/publications/papers/mikolajczyk05.pdf     
Moreover, SuperPoint detectors are trained by using homography adaptation 
https://arxiv.org/pdf/1712.07629.pdf
