### ISSUE TITLE
Packages doesn't set up on python venv

### ISSUE THREAD

**Issue by TJ-seoultech** [luigifreda/pyslam#74]
When I executed install.sh, the main.py didn't work.

$ . install_all_venv.sh  
N.B.: do not forget the dot! (without '/' !)
This will compile the required thirdparty packages and will also activate the created pyslam environment. Now, from the same terminal, you can run:

$ python3 -O main_slam.py
The result was (pyslam) (base) ict-526@ict526-MS-7D32:~/pyslam$ python3 -O main_slam.py

Traceback (most recent call last):
  File "/home/ict-526/pyslam/main_slam.py", line 27, in <module>
    from config import Config
  File "/home/ict-526/pyslam/config.py", line 27, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
I think the packages didn't install in the venv (pyslam). So I manually installed packages(Python 3.6.9, Numpy (1.18.2), OpenCV, PyTorch (>= 1.4.0), Tensorflow-gpu 1.14.0
How can I fix this situation?

After install_all_venv.sh, the pyslam venv support python 3.9.7...

**Comment by luigifreda** [comment]
Hi,
what's your OS? Did you use the right branch?
