### ISSUE TITLE
Want to discard some images, with less than 5 features, in pyslam framework

### ISSUE THREAD

**Issue by abhikaushik1** [luigifreda/pyslam#77]
In my dataset. I have some images with less than 5 keypoints due to which pyslam is not working properly.  I am not able to discard those images inside pyslam framework without disturbing the data flow.

**Comment by Mechazo11** [comment]
Which script are you using? main_vo or main_slam?

**Comment by luigifreda** [comment]
@abhikaushik1 Can you share a video of what you exactly mean?

Having few features in poor light conditions or with an environment not providing enough texture (no image gradients) is a challenging condition in pure visual SLAM.
