### ISSUE TITLE
Question about PLVS

### ISSUE THREAD

**Issue by zhangxuelei86** [luigifreda/pyslam#78]
Dear Luigi Freda，I have seen the demo meshing video of PLVS， can you tell which kind of dense reconstruction method and the meshing method had been used？ I want build a pipeline for spatial mapping and will it in agumented reality. What's the new updates of PLVS，as its a great job. Any answers will be great apperciated for your helps!
Yours, Xuelei Zhang

**Comment by luigifreda** [comment]
Thanks for your interest. There are different volumetric mapping methods available there (TSDF, 3D occupancy mapping, etc, and some variants of these algorithms). I have to find the time (during my free time) to clean up the repo and add documentation.

**Comment by luigifreda** [comment]
Hi,
PLVS is now available on github
https://github.com/luigifreda/plvs
