### ISSUE TITLE
Solving ImportError: ../pyslam/thirdparty/g2opy/lib/g2o.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by Mechazo11** [luigifreda/pyslam#79]
Dear @luigifreda,

Sir, thank you very much for collecting all the necessary packages and providing an easy to follow example in building visual odometry/slam pipeline. 

After following installation instructions, I was getting the following error in a Ubuntu 20.04 machine,

`ImportError: /home/icore_base/PySLAM/pyslam/thirdparty/g2opy/lib/g2o.so: undefined symbol: _Py_ZeroStruct` when executing `python3 simple_test.py` in test/g2o folder. 

However, I found the solution following another github post `https://github.com/PyMesh/PyMesh/issues/59` which suggested we use the following  `cmake ..` command:  `cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3`. 

The changes I made to successfully import g2o in `install_thirdparty.sh` file is as follows

swap `cmake .. $EXTERNAL_OPTION` with `cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3` in line 135.

I hope this helps somebody out who are starting out with the pyslam 

With best regards,
Mechazo11

**Comment by luigifreda** [comment]
Hi,
I am not sure which install procedure you used. Please, take a look at this post
https://github.com/luigifreda/pyslam/issues/105#issuecomment-1902037114
