### ISSUE TITLE
Seeking clarification on the functions with @property decorator in Frame class in frame.py

### ISSUE THREAD

**Issue by Mechazo11** [luigifreda/pyslam#80]
Dear Mr. @luigifreda,

In the Frame class, Tcw, Twc etc. methods are decorated with the @property operator.  Each of these methods has the following line

`with self._lock_pose:`

What is this line doing? Is it related to the threading?

With best,
@Mechazo11

**Comment by luigifreda** [comment]
yes, that allows to safely share data within multiple threads
