### ISSUE TITLE
install_all_venv.sh gives error in pangolin lib

### ISSUE THREAD

**Issue by pisoir** [luigifreda/pyslam#86]
When running the install_all_venv.sh, during the compilation of pangolin, I get the following errors:
```
pyslam/thirdparty/pangolin/src/video/drivers/ffmpeg.cpp:47:41: note: in definition of macro ‘TEST_PIX_FMT_RETURN’
   47 | #  define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
      |                                         ^~~~~~~~~~~
/home/osluciak/code/VSLAM/code/pyslam/thirdparty/pangolin/src/video/drivers/ffmpeg.cpp:47:41: error: ‘AV_PIX_FMT_XVMC_MPEG2_IDCT’ was not declared in this scope; did you mean ‘AV_PIX_FMT_VAAPI_IDCT’?
   47 | #  define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
```

Any idea how to fix it? Thanks.

**Comment by luigifreda** [comment]
Could you please provide more info? 
Which is your target OS? Ubuntu 18, Ubuntu 20, or others? Are you using the right branch?

**Comment by luigifreda** [comment]
Just tried the script `install_all_venv.sh` on a clean docker image of both ubuntu18 and ubuntu20 and it works. 

In any case, that error seems connected to a missing avcodec package. Try to manually install it on your system. For instance, under ubuntu
```
sudo apt install -y libavcodec-dev
```
