### ISSUE TITLE
Can not create "pyslam" environment with  python 3.6.9

### ISSUE THREAD

**Issue by cdva291** [luigifreda/pyslam#88]
Hello, 
From pyenv I tried to install python 3.6.9,  but encountered an following issue. I guess it will affect to the ./install_all_mac_venv.sh:

`python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.9.tar.xz...
-> https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
Installing Python-3.6.9...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.2.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/01/bx2q2rbn099ch5d1gr1zm5fc0000gn/T/python-build.20230217150957.94821
Results logged to /var/folders/01/bx2q2rbn099ch5d1gr1zm5fc0000gn/T/python-build.20230217150957.94821.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.`

Here am I using: 
_MacOS Ventura 13.2.1
_pyenv 2.3.13
_Homebrew 4.0.1

Is there another way that I can still install tensorflow-gnu 1.14.0 with another python's version?

**Comment by luigifreda** [comment]
Hi,
unfortunately, I am not able to provide support under Mac anymore. I will update the READMEs. 
If you have trouble with tensorflow, try this fix 
https://github.com/luigifreda/pyslam/issues/92
I
