### ISSUE TITLE
Camera pose and map covariance

### ISSUE THREAD

**Issue by Edocinghia93** [luigifreda/pyslam#89]
Is it possible to extract the camera poses and map's covariances?
I have noticed that there is a commented line in the file camera_pose.py that does not work though. 
Was/Is this feature programmed to be added?
If so, there is a quick way to do it?

**Comment by luigifreda** [comment]
Hi,
in order to get a covariance estimation you have to interact with g2o during pose optimization and BA (or implement the back-end by yourself). This is something not implemented yet in pyslam. Unfortunately, I do not see a quick way to properly extract the covariance. Maybe in the future.

**Comment by luigifreda** [comment]
This is a newer related issue in which the problem is discussed
https://github.com/luigifreda/pyslam/issues/183
