### ISSUE TITLE
Best brutal force SLAM configuration

### ISSUE THREAD

**Issue by mattiasmar** [luigifreda/pyslam#91]
Hi,
What is the configuration that you would recommend for the SLAM if one wasn't bothered about runtime (far below real time is OK), but want to be as robust as possible, with no lost tracking?

I have a test sequence with some motion blur and a (almost) pure rotation. In the scene  with the rotation, which also happens to have only a few feature points (tens of them) the feature tracking works OK according to the main_vo.py, but the SLAM (main_slam.py) looses the tracking when I reach this scene. I want to bridge this lost of SLAM tracking (without considering compute cost).

Thanks!

**Comment by luigifreda** [comment]
Hi, 
Thanks for your feedback. As explained in the main README, the script `main_vo.py` is a first start to understanding the basics of inter-frame feature tracking and camera pose estimation (there is no triangulation and mapping there). You cannot use it without a ground truth. Not sure about the results you are getting.  

![Screenshot from 2023-10-14 17-04-31](https://github.com/luigifreda/pyslam/assets/10080262/22716ec3-97ca-4eb5-9657-ec2dc421b024)

**Pure rotations** do break **monocular** VO/SLAM (such as pyslam). Indeed, pure rotations prevent triangulation, so no new map points if you look at unexplored/unmapped areas. That means, no map no tracking. 

Low-light condition is another great challenge for indirect (feature-based) tracking. Many SLAM systems have a difficult time to track in such conditions. In some cases, direct (based on photometric error) tracking (or a mixed approach) can give you a more robust performance. 

Unfortunately, I didn't yet have time to identify the BEST brutal force SLAM configuration. It's a work in progress. Feature selection is just a part of the full system. There are many other parameters to tune. As you may know, SLAM systems are complex. 
Please, consider that pyslam is a playground to test local features within a VO/SLAM system. You can have fun yourselves by testing, tweaking, and improving. Let me know. 

Cheers, 
Luigi
