### ISSUE TITLE
MatplotLib Not responding

### ISSUE THREAD

**Issue by Sadegh-Kalami** [luigifreda/pyslam#96]
Hey,
thanks for your great job. I really love what you have done.
Do you mind helping me?
I did all u have said in readme and code is running perfectly, but the matplotlib(matched_points_plt.draw) is not working.
matplotlib is not responding!!!
![image](https://github.com/luigifreda/pyslam/assets/130472385/fe86a54d-e182-4358-9146-dc512a4c0656)

**Comment by luigifreda** [comment]
Could you please share which are your OS and the install procedure you followed?

**Comment by Sadegh-Kalami** [comment]
thanks for you're fast response.
I have ubuntu 18.04 on VMware and I did the below steps to install PySlam:
1. $ git clone --recursive https://github.com/luigifreda/pyslam.git
2. and then install_all.sh
3. running python3 -O main_slam.py
if you need anything else to tell me to provide it for you.
thanks for your time and consideration <3

**Comment by luigifreda** [comment]
Hi,
I see you are using VMWare. Unfortunately, I can't help with that. Virtual machines may cause tons of troubles with viz tools. I recommend using a native Linux system.

**Comment by luigifreda** [comment]
In any case, try to use `install_all_venv.sh` instead of `install_all.sh`. In general, the installation in the virtual environment is more robust.

**Comment by Sadegh-Kalami** [comment]
Appetiate your help and thanks for your support! <3
