### ISSUE TITLE
How to reach estimated X,Y,Z,Yaw,Roll and Pitch

### ISSUE THREAD

**Issue by Sadegh-Kalami** [luigifreda/pyslam#97]
Hey, thanks for your great job, and nice work done.<3
I know how to get XYZ Translation in your code but I have no idea how to get Rotation out of your code.
as far as I know, I think you save poses in a 4x4 homogeneous pose matrix (SE(3) matrix). isn't it right?
please give me a hint.
            self.cur_R = f_cur.pose[:3,:3].T
            self.cur_t = np.dot(-self.cur_R,f_cur.pose[:3,:3])
            print("\n Estimated Translation",self.cur_t)

**Comment by luigifreda** [comment]
Hi,
Thanks for the feedback. 
Yes, you can access the current estimates in that way (commented code 
https://github.com/luigifreda/pyslam/blob/master/slam.py#L700 )
The poses are stored in the map frames and keyframes, which are continuously updated by BA. 
However, if you access a frame/keyframe pose at a certain time during the processing, you'll get the estimate at that specific time (current estimate). Note that BA can reprocess the local map (including the keyframes and points around the frame you considered) at any time later and readjust those estimates. 
It depends on what you want to access and possibly evaluate: current (i.e. online) estimates or final estimates at the end of the trajectory.  

Hope this helps.
Cheers, 
Luigi

**Comment by luigifreda** [comment]
Can you share your code?

**Comment by luigifreda** [comment]
did you check this https://github.com/luigifreda/pyslam/blob/master/slam.py#L705 ?

**Comment by luigifreda** [comment]
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html
`matplotlib.pyplot.scatter` is for drawing 2D points and it only considers the x and the y components. 

The spanning tree you are trying to draw in 2D is an array of 3D points. Why do you want to draw the projection of the 3D camera positions on the xy plane?

**Comment by hbonnavaud** [comment]
Because I don't care about the Z axis. Basically I want to plot the x y estimated position of the car. (I think it makes sens). I'm looking into the link to slam.py you shared above

**Comment by luigifreda** [comment]
You are assuming the Z axis is vertical. That's not correct. 
This is the standard convention in computer vision when setting the camera frame 
https://docs.opencv.org/4.x/pinhole_camera_model.png
https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html

**Comment by hbonnavaud** [comment]
Yes but still, scatter X and Z, X and Y, or Y and Z don't give me nothing similar to the trajectory plotted in pangolin.

**Comment by hbonnavaud** [comment]
I think there is an error in https://github.com/luigifreda/pyslam/blob/master/slam.py#L705 


```
    def update_history(self):
        f_cur = self.map.get_frame(-1)
        self.cur_R = f_cur.pose[:3,:3].T
        self.cur_t = np.dot(-self.cur_R,f_cur.pose[:3, 3])
        if (self.init_history is True) and (self.trueX is not None):
            self.t0_est = np.array([self.cur_t[0], self.cur_t[1], self.cur_t[2]])  # starting translation
            self.t0_gt  = np.array([self.trueX, self.trueY, self.trueZ])           # starting translation
        if (self.t0_est is not None) and (self.t0_gt is not None):
            p = [self.cur_t[0]-self.t0_est[0], self.cur_t[1]-self.t0_est[1], self.cur_t[2]-self.t0_est[2]]   # the estimated traj starts at 0
            self.traj3d_est.append(p)
            self.traj3d_gt.append([self.trueX-self.t0_gt[0], self.trueY-self.t0_gt[1], self.trueZ-self.t0_gt[2]])
            self.poses.append(poseRt(self.cur_R, p))
```
`self.init_history` is always True, so `self.cur_t[0]-self.t0_est[0]` is always equal to 0. right? What am I missing here?

**Comment by hbonnavaud** [comment]
Well, the update history function give me the same that what I had before. The estimated position projected on the XZ plan is the red curve here. 

![image](https://github.com/luigifreda/pyslam/assets/45778095/617acfbe-5242-4df2-a079-c5e309fdf3f8)

**Comment by hbonnavaud** [comment]
> "Keep in mind that, in visual SLAM, the pose is always estimated w.r.t. the first camera frame."
Yes I know, I don't really care about the grount truth here. All I want is to be able to extract a trajectory similar to the green one on the left (in pangolin). Aka a trajectory that can match the ground trust after beeing scaled, rotated and translated

**Comment by luigifreda** [comment]
I think you may want to consider the different scales on the two 2D axes of your 2D scatter plot. 

https://matplotlib.org/stable/gallery/subplots_axes_and_figures/axis_equal_demo.html

**Comment by hbonnavaud** [comment]
Wow it was the issue ... it was so simple after all thx a lot for your time. Sorry to bothered you.

**Comment by pse0311** [comment]
Hello,

I am finding your creation very useful, thanks to you.

I'm interested in obtaining the **x, y, z coordinate values** stored in the Map Viewer. Could you please guide me on how to do this?

Thank you.
