### ISSUE TITLE
Getting error when running the slam 

### ISSUE THREAD

**Issue by AyonRRahman** [luigifreda/pyslam#98]
Traceback (most recent call last):
  File "main_slam.py", line 29, in <module>
    from slam import Slam, SlamState
  File "/home/ayon/git/pyslam/slam.py", line 35, in <module>
    from map import Map
  File "/home/ayon/git/pyslam/map.py", line 41, in <module>
    import optimizer_g2o 
  File "/home/ayon/git/pyslam/optimizer_g2o.py", line 36, in <module>
    def bundle_adjustment(keyframes, points, local_window, fixed_points=False, verbose=False, rounds=10, use_robust_kernel=False, abort_flag=g2o.Flag()):
AttributeError: module 'g2o' has no attribute 'Flag'

**Comment by luigifreda** [comment]
Hi,
thank you for the feedback. 

Can you please share your OS and the install procedure you followed? 
Are you sure you selected the correct branch for your OS?
It sounds like your installation wasn't correctly completed. 

Please, check this related issue https://github.com/luigifreda/pyslam/issues/43
and follow these steps: 
- check you are on the correct `pyslam` branch according to your OS
- check you have `rsync` installed in your OS (it should be installed by pyslam scripts)
- use the `pyslam` install scripts
- open a terminal in the root folder of the repo 
- clean with
`$ ./clean.sh`
- launch a new install with
`$ ./install_all_venv.sh`
- check that you have a file like `thirdparty/g2opy/lib/g2o.cpython-36m-x86_64-linux-gnu.so`?
If not then we have a problem with the compilation of `g2o`.

In the above steps, follow the venv install procedure reported here
https://github.com/luigifreda/pyslam/blob/master/PYTHON-VIRTUAL-ENVS.md
Don't forget to activate the pyslam environment before trying to running pyslam scripts
https://github.com/luigifreda/pyslam/blob/master/PYTHON-VIRTUAL-ENVS.md#activate-the-created-pyslam-environment

Let me know. 
Cheers. 
Luigi
