### ISSUE TITLE
Failed Building wheel for opencv-contrib-python

### ISSUE THREAD

**Issue by HamzaOuajhain** [luigifreda/pyslam#99]
Beginner at SLAM, I have encountered a problem with the full installation, I am currently using ubuntu 18.04 with wsl2 and trying the installation before I install ubuntu in a physical device. 

![image](https://github.com/luigifreda/pyslam/assets/121122945/b2c3ff82-b021-458b-aa4e-bd666445107a)

you did mention in the TROUBLESHOOTING.md

In order to use [non-free OpenCV features](https://stackoverflow.com/questions/50467696/pycharm-installation-of-non-free-opencv-modules-for-operations-like-sift-surf) (i.e. **SURF**, etc.), you need to install the module `opencv-contrib-python` built with the enabled option `OPENCV_ENABLE_NONFREE`. You can find SURF availalble in `opencv-contrib-python 3.4.2.16`: this can be installed by running
```
$ pip3 uninstall opencv-contrib-python
$ pip3 install opencv-contrib-python==3.4.2.16
```
what I want to know since the installation finished will that cause me any problem in the future if I don't use the SURF/SIFT feature ?

![image](https://github.com/luigifreda/pyslam/assets/121122945/fd66ebb6-99c3-4e45-9f7d-4897c7e5f658)

**Comment by luigifreda** [comment]
Hi, 
thanks for the feedback. I don't see that error in a native ubuntu 18 and in a docker container ubuntu:18.04. At present, I am not able to easily check it in Windows. I am glad you got it built in any case.

> what I want to know since the installation finished will that cause me any problem in the future if I don't use the SURF/SIFT feature ?

No, the usage of SIFT and SURF is just an option you have. It is not compulsory.
